#!/usr/bin/env bash
#
# test/workflow-race-guard.sh — verifies scripts/push-with-race-guard.sh
# against a real git remote (a bare repository), reproducing every history the
# bot workflows can end up in, including the exact push-race that killed the
# 2026-09-18 post-merge ingest run on main (IRREGULARITIES.md #41).
#
# Run directly:  bash test/workflow-race-guard.sh
# (also chained into `npm run test:all`)
#
# Scenarios:
#   1. clean push (no race)
#   2. nothing to commit -> no commit is created
#   3. race, disjoint files -> rebase resolves it, both commits land
#   4. race + conflict on a GENERATED module -> regeneration resolves it,
#      no conflict markers ever reach the remote
#   5. race + conflict on a DATA file -> the run aborts the rebase and exits
#      non-zero (the job must be re-run; data is re-fetched from the exchange)
#   6. REGRESSION for the 2026-09-18 failure: a tracked file the old workflow
#      forgot to `git add` (src/forecast-data.js then, src/generated.js here)
#      must now be committed by the guard, so the rebase can start at all.

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT="${ROOT}/scripts/push-with-race-guard.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

PASS=0
FAIL=0
ok()   { PASS=$((PASS + 1)); echo "  ok   - $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL - $1"; }
check() { # check <description> <command...>
  local desc="$1"; shift
  if "$@" >/dev/null 2>&1; then ok "$desc"; else fail "$desc"; fi
}

# ---------------------------------------------------------------------------
# Fixture: origin (bare "GitHub"), bot (the racing workflow), runner (ours).
# src/generated.js is a generated module: a pure function of data/*.txt,
# regenerated by ./regen.sh — the stand-in for generate-history-module.mjs.
# ---------------------------------------------------------------------------
make_fixture() {
  rm -rf "$TMP/origin" "$TMP/bot" "$TMP/runner" "$TMP/regen.sh"
  git init --bare -q -b main "$TMP/origin"
  git clone -q "$TMP/origin" "$TMP/bot"
  git -C "$TMP/bot" config user.email bot@example.com
  git -C "$TMP/bot" config user.name bot
  mkdir -p "$TMP/bot/data" "$TMP/bot/src"
  printf 'base-source\n'   > "$TMP/bot/data/source.txt"
  printf 'base-other\n'    > "$TMP/bot/data/other.txt"
  printf 'base-source\nbase-other\n' > "$TMP/bot/src/generated.js"
  git -C "$TMP/bot" add -A
  git -C "$TMP/bot" commit -qm 'base'
  git -C "$TMP/bot" push -q origin main

  git clone -q "$TMP/origin" "$TMP/runner"
  git -C "$TMP/runner" config user.email runner@example.com
  git -C "$TMP/runner" config user.name runner
  # regen.sh lives OUTSIDE the runner tree (it must never be committed by the
  # guard's `git add -A`) and regenerates the module from the MERGED data tree
  printf '#!/usr/bin/env bash\ncat data/source.txt data/other.txt > src/generated.js\n' \
    > "$TMP/regen.sh"
  chmod +x "$TMP/regen.sh"
}

run_guard() { # run_guard <commit message>
  ( cd "$TMP/runner" &&
    REGENERATE_CMD="$TMP/regen.sh" \
    GENERATED_PATHS="src/generated.js" \
    GIT_REMOTE=origin \
    bash "$SCRIPT" "$1" main ) >>"$TMP/guard.log" 2>&1
}

origin_head() { git -C "$TMP/origin" rev-parse main; }
runner_head() { git -C "$TMP/runner" rev-parse HEAD; }
origin_file() { git -C "$TMP/origin" show "main:$1" 2>/dev/null; }

echo "1. clean push (no race)"
make_fixture
BEFORE="$(origin_head)"
printf 'new-source\n' > "$TMP/runner/data/source.txt"
if run_guard 'runner commit'; then
  ok "guard exits 0"
else
  fail "guard exits 0"
fi
check "origin advanced by exactly one commit" test "$(git -C "$TMP/origin" rev-list --count main)" = 2
check "origin carries the runner's data" test "$(origin_file data/source.txt)" = "new-source"
check "runner HEAD == origin main" test "$(runner_head)" = "$(origin_head)"

echo "2. nothing to commit"
make_fixture
if run_guard 'should not exist'; then
  ok "guard exits 0"
else
  fail "guard exits 0"
fi
check "no commit was created" test "$(git -C "$TMP/origin" rev-list --count main)" = 1

echo "3. race with disjoint files -> rebase resolves"
make_fixture
printf 'runner-source\n' > "$TMP/runner/data/source.txt"
# the OTHER bot pushes while our run is working
printf 'bot-other\n' > "$TMP/bot/data/other.txt"
git -C "$TMP/bot" add -A && git -C "$TMP/bot" commit -qm 'bot commit'
git -C "$TMP/bot" push -q origin main
if run_guard 'runner commit'; then
  ok "guard exits 0 after the race"
else
  fail "guard exits 0 after the race"
fi
check "both commits landed" test "$(git -C "$TMP/origin" rev-list --count main)" = 3
check "origin has the runner's data" test "$(origin_file data/source.txt)" = "runner-source"
check "origin has the bot's data" test "$(origin_file data/other.txt)" = "bot-other"

echo "4. race + conflict on the generated module -> regeneration resolves it"
make_fixture
# our run changes data and the module step regenerates the module from it
printf 'runner-source\n' > "$TMP/runner/data/source.txt"
printf 'runner-source\nbase-other\n' > "$TMP/runner/src/generated.js"
# the other bot changes DIFFERENT data and regenerates the same module
printf 'bot-other\n' > "$TMP/bot/data/other.txt"
printf 'base-source\nbot-other\n' > "$TMP/bot/src/generated.js"
git -C "$TMP/bot" add -A && git -C "$TMP/bot" commit -qm 'bot commit'
git -C "$TMP/bot" push -q origin main
if run_guard 'runner commit'; then
  ok "guard exits 0 after the conflict"
else
  fail "guard exits 0 after the conflict"
fi
check "both commits landed" test "$(git -C "$TMP/origin" rev-list --count main)" = 3
check "origin module regenerated from merged data (no markers)" \
  test "$(origin_file src/generated.js)" = "runner-source
bot-other"
check "origin has the bot's data too" test "$(origin_file data/other.txt)" = "bot-other"

echo "5. race + conflict on a DATA file -> abort, exit non-zero"
make_fixture
printf 'runner-source\n' > "$TMP/runner/data/source.txt"
printf 'bot-source\n' > "$TMP/bot/data/source.txt"
git -C "$TMP/bot" add -A && git -C "$TMP/bot" commit -qm 'bot commit'
git -C "$TMP/bot" push -q origin main
BEFORE="$(origin_head)"
if run_guard 'runner commit'; then
  fail "guard exits non-zero on an unresolvable data conflict"
else
  ok "guard exits non-zero on an unresolvable data conflict"
fi
check "origin untouched by the failed run" test "$(origin_head)" = "$BEFORE"
check "runner left with its own commit intact (rebase aborted cleanly)" \
  test "$(git -C "$TMP/runner" log --format=%s -1)" = "runner commit"
check "no conflict markers committed anywhere" \
  test -z "$(git -C "$TMP/origin" show main:data/source.txt | grep -F '<<<' || true)"

echo "6. regression 2026-09-18: tracked-but-unstaged file must not block the rebase"
make_fixture
# the run rewrote data AND a tracked module but NOTHING is committed yet —
# the old workflow committed only `data/`, leaving the module unstaged
printf 'runner-source\n' > "$TMP/runner/data/source.txt"
printf 'runner-source\nbase-other\n' > "$TMP/runner/src/generated.js"
# the other bot races us with a disjoint change
printf 'bot-other\n' > "$TMP/bot/data/other.txt"
git -C "$TMP/bot" add -A && git -C "$TMP/bot" commit -qm 'bot commit'
git -C "$TMP/bot" push -q origin main
if run_guard 'runner commit'; then
  ok "guard survives the exact 2026-09-18 race"
else
  fail "guard survives the exact 2026-09-18 race"
fi
check "the once-forgotten module is committed too" \
  test "$(origin_file src/generated.js)" = "runner-source
base-other"
check "both commits landed" test "$(git -C "$TMP/origin" rev-list --count main)" = 3

echo
echo "passed ${PASS}, failed ${FAIL}"
[ "$FAIL" = 0 ]
