/**
 * KalshiPaperSim — Accumulated Kalshi history (GENERATED — DO NOT EDIT)
 * =====================================================================
 * Generated by scripts/generate-history-module.mjs from data/history/*.json —
 * the store written by scripts/ingest-history.mjs from the official Kalshi API.
 * Run `npm run build` or the ingest workflow to regenerate it.
 *
 * Every bar below is copied verbatim from a live response to
 *   GET /series/{series_ticker}/markets/{ticker}/candlesticks
 *   https://docs.kalshi.com/api-reference/market/get-market-candlesticks
 * Order-book snapshots are deliberately excluded (they stay in data/history/ for
 * the Node server; they are far too large for a browser module).
 *
 * 0 market(s) · 0 daily bar(s) · generated 2026-09-17T23:05:47.795Z
 */

export const ACCUMULATED_HISTORY = {
  "generatedAt": "2026-09-17T23:05:47.795Z",
  "present": false,
  "sourceDir": "data/history",
  "sourceFiles": 0,
  "marketCount": 0,
  "barCount": 0,
  "manifestGeneratedAt": "2026-09-17T23:01:29.248Z",
  "manifestTotals": {
    "markets": 3,
    "barsAdded": 0,
    "barsStored": 136,
    "conflicts": 0,
    "failures": 0
  },
  "markets": {}
};

/** Every bar stored for one ticker, or null when that market is not tracked. */
export function getAccumulatedBars(ticker) {
  const m = ACCUMULATED_HISTORY.markets[ticker];
  return m ? m.bars : null;
}

/** The raw stored record for one ticker (bars + captured market object). */
export function getAccumulatedMarket(ticker) {
  return ACCUMULATED_HISTORY.markets[ticker] || null;
}

/** Tickers with at least `minBars` stored daily bars, sorted. */
export function getAccumulatedTickers(minBars = 0) {
  return Object.values(ACCUMULATED_HISTORY.markets)
    .filter((m) => m.bar_count >= minBars)
    .map((m) => m.ticker)
    .sort();
}
